### ISSUE TITLE
Several naming mistakes

### ISSUE THREAD

**Issue by ZAX130** [tzayuan/TransMatch_TMI#1]
![image](https://github.com/tzayuan/TransMatch_TMI/assets/43944700/c8aef82b-ce18-45b1-a7ae-7fc7c19957d9)
![image](https://github.com/tzayuan/TransMatch_TMI/assets/43944700/9522e913-7c14-411f-be2e-39e21aa30a3e)

**Comment by tzayuan** [comment]
Hi, @ZAX130 
Thank you for pointing out the error in the code. I will update the code after review. Due to the recent change of work school and hardware problems, this time may be extended, I'm sorry, I will update the issue after feedback.

**Comment by tzayuan** [comment]
The code has been re-reviewed and debugged, and it is now ready for direct training and inference on the provided LPBA40 dataset.
