### ISSUE TITLE
Pre-trained Model Weights

### ISSUE THREAD

**Issue by Promise13** [tzayuan/TransMatch_TMI#10]
Thank you for sharing the code for TransMatch. However, due to the large size of the OASIS dataset, we are unable to train the model. Could you please share the pre-trained weights with us? We would like to use it as a baseline for comparison.

**Comment by tzayuan** [comment]
Apologies, but we currently lack the resources for retraining. Based on our previous tests, a 24GB GPU can train with batch size=1 (VRAM usage: 24,177MB). Please ensure no other programs are loaded in GPU memory.
