### ISSUE TITLE
 visualization

### ISSUE THREAD

**Issue by yesstarA** [tzayuan/TransMatch_TMI#2]
Thank you for your wonderful work! I think the visualization in your paper is very beautiful, and I look forward to your subsequent upload of visualization code!

**Comment by tzayuan** [comment]
Sorry for the slow response due to project reasons. Part of the visualization code in the article is already in the [VisualTools](https://github.com/tzayuan/TransMatch_TMI/tree/main/VisualTools) path of the repository. May I ask which specific visualization cannot be implemented?

**Comment by yesstarA** [comment]
Thanks for the reply! I'm getting started with learning image registration, and I do have some confusion about the deformation field (RGB) & deformation field (Grid) of the qualitative maps in your paper. Maybe these questions are very basic, but this is really important to me.

**Comment by tzayuan** [comment]
Sorry to reply late, you could use ITK-SNAP(http://www.itksnap.org/docs/viewtutorial.php) for visual the deformation field. Here is a example file of deformation field, you could try it by yourself. 

https://cowtransfer.com/s/c065393e593947 [ S10_flow.nii.gz ] key: gjcral
