### ISSUE TITLE
HD

### ISSUE THREAD

**Issue by shy922** [tzayuan/TransMatch_TMI#3]
How to calculate HD？

**Comment by tzayuan** [comment]
sorry for reply so late, you could refer this link to calculate the HD metrics: https://pymia.readthedocs.io/en/latest/examples.evaluation.basic.html

**Comment by tzayuan** [comment]
notice that you could fix some code of this library to satisfy your need. :)

**Comment by shy922** [comment]
Thanks. How is the Jacobian Map visualized?

**Comment by tzayuan** [comment]
please refer to [URL](https://www.nitrc.org/projects/dfviewer/)

**Comment by shy922** [comment]
Sorry, I can't visualize this Jacobian Map correctly, what image should I open with DFViewer to visualize correctly, if so, can you provide the method of visualization through code?

**Comment by tzayuan** [comment]
you could refer to my Train.py and Infer.py script to genertate some flow.nii.gz and to visual it.

**Comment by shy922** [comment]
Thank you.
