### ISSUE TITLE
作者你好，请问这里fixed输入movinglwsa是否有误

### ISSUE THREAD

**Issue by RuoYu-MENG** [tzayuan/TransMatch_TMI#6]
![07A5394E-62D6-441A-90A2-2DF63A49CF32](https://github.com/tzayuan/TransMatch_TMI/assets/143580748/6c2ef862-ebc4-40d9-80fc-9406976327f0)

**Comment by tzayuan** [comment]
您好，

您的理解是有道理的，但是存在一些实验验证的考虑，如下。

在实验验证方法时，这个地方曾尝试过共享参数与独立参数两种方案，即
（1）
`
moving_fea = self.moving_lwsa(moving_input)
fixed_fea = self.fixed_lswa(fixed_input)
`
和
（2）
`
moving_fea = self.moving_lwsa(moving_input)
fixed_fea = self.moving_lswa(fixed_input)
`

有以下两点考虑和验证：
1. 参数不共享（1）时显存占用会增加很多，如paper中memory usage所示，目前参数共享的方案已几乎榨干24G显卡的显存；
2. 通过参数共享的方式（2），可以加快模型的迭代收敛，一个比较感性的思考角度是moving image和fixed image从内容表达上讲其实都是intensity-based的图像(如 brain MRI T1W)，他们并不存在学习内容概念上的不一致性。

**Comment by RuoYu-MENG** [comment]
感谢回答
