### ISSUE TITLE
code issues in trainin.py

### ISSUE THREAD

**Issue by 0305sherrynan** [tzayuan/TransMatch_TMI#9]
Shouldn't the similarity loss function be calculated in the source code for warped images and fixed images?

![Snipaste_2024-09-19_17-49-39](https://github.com/user-attachments/assets/5cc17dfe-0a4d-478a-8b9d-becc47e18947)

**Comment by tzayuan** [comment]
Hi, @0305sherrynan 

I apologise for not responding in time.
Plz see the definition of the `def forward(self, moving_Input, fixed_Input)` function formal parameter in the `Models/TransMatch.py` script.

If you still have questions, please feel free to ask!

Zeyuan
